# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5ad999bbd045203e6354b3ef7075b3fa8684202b99687b3e443c5cb9d989bb06d73bbc0ee253f1d3617707dd2af4b0c795f5ac1e9567d9c34432c5948283287

test:
  secret_key_base: 1bda945c20b43f831bcd487696cf04690af3658cde8fc3e10f6a4d97f416bbb05e8a73e85d2549bbc234e320e9e5f81a31cfb261c16b81df7f2b74cf6de362f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
